sudo: required
services:
  - docker

before_install:
  - docker build -t serdarp/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run serdarp/react-test npm test -- --coverage

after_success:
  - docker build -t serdarp/multi-client ./client
  - docker build -t serdarp/multi-nginx ./nginx
  - docker build -t serdarp/multi-server ./server
  - docker build -t serdarp/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" |Â docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push serdarp/multi-client
  - docker push serdarp/multi-nginx
  - docker push serdarp/multi-server
  - docker push serdarp/multi-worker